apiVersion: v1
kind: Service
metadata:
  name: echotalk-mailpit
  labels:
    app: echotalk-mailpit
spec:
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
  selector:
    app: echotalk-mailpit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echotalk-mailpit
  labels:
    app: echotalk-mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echotalk-mailpit
  template:
    metadata:
      labels:
        app: echotalk-mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.27
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 1025
            - name: web
              containerPort: 8025
