apiVersion: v1
kind: Secret
metadata:
  name: echotalk-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "echotalk_secret"
  SPRING_DATASOURCE_PASSWORD: "echotalk_secret"
  JWT_SECRET: "echotalk-super-secret-jwt-key-change-in-production-2024"
  MAIL_PASSWORD: ""
  TURN_CREDENTIAL: "change-this-turn-password"
